### ISSUE TITLE
backup breaks up

### ISSUE THREAD

**Issue by teefixx** [mr-manuel/raspberry-pi-backup#1]
Hi mr-manuel

Tried to use your backup script on a raspberryPi 3B using VenusOS 3.00-32
The backup breaks up in the middle and I assume, that the share cannot be mounted as the script cannot unmount at the end. Having a look with df shows, that there is no mount.

~~~
root@PiVenusOS:/data/etc/raspberry-pi-backup# sudo ./backup.sh
117000000 bytes (117 MB, 112 MiB) copied, 11 s, 10.3 MB/s
/data/etc/raspberry-pi-backup/ext/dd: error writing '/mnt/backup/PiVenusOS/Backup_PiVenusOS_20230417_095734.img': No space left on device
122+0 records in
121+0 records out
121827328 bytes (122 MB, 116 MiB) copied, 12.0684 s, 10.1 MB/s
head: invalid number '-5'
umount: /mnt/backup: not mounted.
root@PiVenusOS:/data/etc/raspberry-pi-backup# 
~~~

tried to mount the share manally, but didn't work either...
I got no error message, the mount command has no output.

This script worked earlier, when I used a lower version of VenusOS, but unfortunately not sure which version.

**Comment by mr-manuel** [comment]
The message says no space left. Did you check that on the remote device?

**Comment by teefixx** [comment]
on the remote device there is enough free space, I checked it. 
The problem I see is, that remote location cannot be mounted from venusOS. The script runs to the end after the error and tries to unmount the share. This generates another error, as the share is not mounted... Even if I try it manually, just for testing purposes, I cannot get a connection. 
If I try it from my computer (MacOS and Windows), the share can be mounted and written to it...

When I try to connect manually from venusOS, use the following command line:

sudo mount -t cifs -o username=VenusOS //192.168.1.10/volume1/VenusOS-Backup /mnt/test

It's odd, that there is no output from this command, as well no error message... Still the share is not mounted.
Is it possible, that the mount.cifs and mount.nfs are not compatible with VenusOS 3.00?

**Comment by mr-manuel** [comment]
Unfortunately you don't see much on busybox. Have you another Raspberry Pi where you can execute the commands with Raspian?

Maybe it has to do something with the SMB version.

**Comment by teefixx** [comment]
good idea. I tried this on a raspbian ver10 pi.
it worked flawless with SMB and NFS. Taking exactly the same command to VenusOS does nothing...

**Comment by mr-manuel** [comment]
Check, if the `mount.cifs` was copied over to `/sbin` and has the correct permissions.

https://github.com/mr-manuel/raspberry-pi-backup/blob/5ffbf98a948c6ff9964831e34e492a66d8b0db37/install-backup.sh#L39-L43

**Comment by teefixx** [comment]
tried this before, gave 777 to both files in sbin. Now added the u+s but no change...
is there something else missing in Venus OS?

**Comment by mr-manuel** [comment]
Did you check the SMB versions on the server? Try to enable/disable SMB1.1, 2.0, 3.0. I will reinstall my Venus OS, if I find time and test it again.

**Comment by teefixx** [comment]
tried this already, the odd thing ist that neither SMB nor NFS work, while on the two other Pi I have both work...

**Comment by teefixx** [comment]
no need to test anymore. 
I found the culprit: both files, mount.nfs and mount.cifs had 0 byte size. Didn't check that before...
I deleted them and recopied them and now it works to connect.

many thanks for your effort!!!

**Comment by mr-manuel** [comment]
You're welcome :-)
