### ISSUE TITLE
NVME Support

### ISSUE THREAD

**Issue by iceyman** [mr-manuel/raspberry-pi-backup#10]
G'day mate just wondering if you could add NVME support at all like add a section we can choose either nvme or sdcard ?

**Comment by mr-manuel** [comment]
But how would you restore the backup then?

Have you a Rasbperry Pi with NVMe?

You could change that line easily to match the NVMe path:

https://github.com/mr-manuel/raspberry-pi-backup/blob/3b3089299e3319f55cc16b6d9b900c5c219185ca/raspberry-pi-backup/backup.sh#L84

for example

```bash
 if [ "$(ps | grep -c 'dd if=/dev/nvme0n1')" -gt 1 ]; then
```

**Comment by iceyman** [comment]
Restore it via imager or whatever to nvme as u can boot it
________________________________

**Comment by iceyman** [comment]
G'day mate yes i have changed a few lines from 

```
 if [ "$(ps | grep -c 'dd if=/dev/mmcblk0')" -gt 1 ]; then
        echo "Backup already running. Exiting..."
        echo
        exit
    fi
    # create backup
    echo "Using script dd for backup."
    "${SCRIPT_DIR}/ext/dd" if=/dev/mmcblk0 of="${BACKUP_PATH}/${BACKUP_NAME}_$(date +%Y%m%d_%H%M%S).img" bs=1MB status=progress

# if not use the system dd
else
    # check if backup is already running
    if [ "$(ps -aux | grep -c 'dd if=/dev/mmcblk0')" -gt 1 ]; then
        echo "Backup already running. Exiting..."
```
To

```
 if [ "$(ps | grep -c 'dd if=/dev/nvme0n1')" -gt 1 ]; then
        echo "Backup already running. Exiting..."
        echo
        exit
    fi
    # create backup
    echo "Using script dd for backup."
    "${SCRIPT_DIR}/ext/dd" if=/dev/nvme0n1 of="${BACKUP_PATH}/${BACKUP_NAME}_$(date +%Y%m%d_%H%M%S).img" bs=1MB status=progress

# if not use the system dd
else
    # check if backup is already running
    if [ "$(ps -aux | grep -c 'dd if=/dev/nvme0n1')" -gt 1 ]; then
        echo "Backup already running. Exiting..."
```
And works Fine :D

But how would you restore the backup then? Same as before mate you can boot a NVME and also write to an NVME is you have [usb to nvme](https://www.amazon.com.au/Dpofirs-Adapter-Supports-10Gbps-Dpofirs7u5149yrgc/dp/B0BVG44TRL/ref=sr_1_3?crid=1AXX372LCJXNQ&dib=eyJ2IjoiMSJ9.FTx98mHLAjj5dG0-WN_q6HENwFqoCm6v_nMlDJFCXS9mI_1Wl3zNSkjkzGIIE9OPLmkfZXejCxI6WcD-35psZsMZ_zOudPu2BpUHGq7vRG-PzCudzl8T4X2vlybnjmC5SlEUAf5Rpv5ccN-qCtKgKQOO343ReiLcBcSJ8Ep-0RQVure2J4y-zCTmk-DAWhh8qdm4go9WggMi0O3rbGnXDzDy-yhbfzhRkcT8q6zqTVH7yE5QVTTGVvOQOYeNMhV8ZIFR_tVX9Ak5mX8Rosh3S0cgPFeL3b_nrET_J6GTbHw.wkozNzZb0yyy0_901Xvh_CK8z5WqhU7G0SfYbGJme7s&dib_tag=se&keywords=usb+to+nvme&qid=1724899346&s=automotive&sprefix=usb+to+nvm%2Cautomotive%2C351&sr=1-3-catcorr)

Have you a Rasbperry Pi with NVMe? Yes i have a pi4 and a pi5 setup and i have used your script to back them up after changes

**Comment by iceyman** [comment]
Thanks mate :D
