### ISSUE TITLE
mount error(95)

### ISSUE THREAD

**Issue by jhaertf** [mr-manuel/raspberry-pi-backup#11]
I have the following error on my venus os device: 

```
Mounting "//192.168.0.1/VenusOSBackup" to "/mnt/backup"...
mount error(95): Operation not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
Error when mounting the remote path.
```

What did i do wrong? Thanks upfront!

**Comment by mr-manuel** [comment]
Could be many things. Hard to say without additional info.

1. On what device is your SMB share located?
2. Which SMB protocols are accepted?
3. Is the share authenticated and have the right permissions?
4. Does a ping work?
5. What are your settings in the script?
6. Did you get errors when running the installation script?
7. Does it work from another device? Normally the path is case sensitive on Linux.
