### ISSUE TITLE
Error loading library

### ISSUE THREAD

**Issue by dmsims** [mr-manuel/raspberry-pi-backup#2]
Installed on Venus v 3.00~22

I edited backup.sh for the share

```bash
2023-06-07 05:26:31 (1.10 MB/s) - ‘/tmp/master.zip’ saved [92757]

Archive:  /tmp/master.zip
   creating: raspberry-pi-backup-master/
  inflating: raspberry-pi-backup-master/LICENSE
  inflating: raspberry-pi-backup-master/README.md
  inflating: raspberry-pi-backup-master/install-backup.sh
   creating: raspberry-pi-backup-master/raspberry-pi-backup/
  inflating: raspberry-pi-backup-master/raspberry-pi-backup/backup.sh
   creating: raspberry-pi-backup-master/raspberry-pi-backup/ext/
  inflating: raspberry-pi-backup-master/raspberry-pi-backup/ext/dd
  inflating: raspberry-pi-backup-master/raspberry-pi-backup/ext/mount.cifs
  inflating: raspberry-pi-backup-master/raspberry-pi-backup/ext/mount.nfs

The installation was successful.
Now you have to change the default parameters of the script and setup a cronjob to run automatically "/data/etc/raspberry-pi-backup/backup.sh" on your desire.

root@raspberrypi2:~# /data/etc/raspberry-pi-backup/backup.sh
/sbin/mount.cifs: error while loading shared libraries: libcap-ng.so.0: cannot open shared object file: No such file or directory
mkdir: can't create directory '/mnt/backup/Backups/raspberrypi2': No such file or directory
/data/etc/raspberry-pi-backup/ext/dd: failed to open '/mnt/backup/Backups/raspberrypi2/Backup_raspberrypi2_20230607_053424.img': No such file or directory
ls: /mnt/backup/Backups/raspberrypi2/Backup_raspberrypi2*: No such file or directory
head: invalid number '-5'
umount: can't unmount /mnt/backup: Invalid argument
```

**Comment by mr-manuel** [comment]
Hello,

it seems that the `mount.cifs` was not copied. Could you please re-run to install the latest version I releases right now?

```bash
wget -O install-backup.sh https://raw.githubusercontent.com/mr-manuel/raspberry-pi-backup/master/install-backup.sh
bash install-backup.sh
```

**Comment by dmsims** [comment]
Thanks for the reply

I reinstalled

root@raspberrypi2:~# /data/etc/raspberry-pi-backup/backup.sh
/sbin/mount.cifs: error while loading shared libraries: libcap-ng.so.0: cannot open shared object file: No such file or directory

![pi-mounts](https://github.com/mr-manuel/raspberry-pi-backup/assets/4712953/bb72c589-40d3-4188-a230-cf8eae54d7c8)

**Comment by mr-manuel** [comment]
Maybe this has to do something with the SMB version. Could you try with another share from your Windows Computer for example?

Have you installed the Venus OS large or the normal one?

Can you post the output of `ls -l /lib/libcap*` or a screenshot like above?

**Comment by dmsims** [comment]
Venus is normal

root@raspberrypi2:~# ls -l /lib/libcap*
lrwxrwxrwx    1 root     root            14 Mar  5 12:04 /lib/libcap.so.2 -> libcap.so.2.32
-rw-r--r--    1 root     root         23516 Mar  5 12:04 /lib/libcap.so.2.32

I put the debug on - this is a share on a Synology Nas (I tried the IP address as well)
I also tried a Windows 11 PC

+ BACKUP_REMOTE_MOUNT=//nas-thesims/
+ BACKUP_SUBFOLDER=venus/
+ BACKUP_REMOTE_MOUNT_USER=*****
+ BACKUP_REMOTE_MOUNT_PW=******
+ BACKUP_COUNT=5
++ hostname
+ BACKUP_HOSTNAME=raspberrypi2
+++ dirname -- /data/etc/raspberry-pi-backup/backup.sh
++ cd -- /data/etc/raspberry-pi-backup
++ pwd
+ SCRIPT_DIR=/data/etc/raspberry-pi-backup
+ BACKUP_MOUNT=/mnt/backup
+ BACKUP_PATH=/mnt/backup/venus/raspberrypi2
+ BACKUP_NAME=Backup_raspberrypi2
+ '[' '!' -d /mnt/backup ']'
+ mount -t cifs -o user=*****,password=******,rw,file_mode=0777,dir_mode=0777 //nas-thesims/ /mnt/backup
/sbin/mount.cifs: error while loading shared libraries: libcap-ng.so.0: cannot open shared object file: No such file or directory
+ '[' 127 -ne 0 ']'
+ echo 'Error during mounting the remote path.'
Error during mounting the remote path.
+ exit

**Comment by mr-manuel** [comment]
Ok, I found the issue. In the normal Venus OS this library is missing. I will add it to the driver.

**Comment by mr-manuel** [comment]
> ```shell
> wget -O install-backup.sh https://raw.githubusercontent.com/mr-manuel/raspberry-pi-backup/master/install-backup.sh
> bash install-backup.sh
> ```

Can you run this commands again?

**Comment by dmsims** [comment]
Progress!

root@raspberrypi2:~#  /data/etc/raspberry-pi-backup/backup.sh
mkdir: can't create directory '/mnt/backup/Backups/raspberrypi2': No such file or directory
/data/etc/raspberry-pi-backup/ext/dd: failed to open '/mnt/backup/Backups/raspberrypi2/Backup_raspberrypi2_20230607_133019.img': No such file or directory
Error during backup of the system.

**Comment by mr-manuel** [comment]
Please put trippe backticks \`\`\` in the line before and after the code/logs for correct formatting.

Do you see the NAS content under `/mnt/backup`? If yes, are you able to write a new file to this folder?

Did you reboot after all the tests?

**Comment by dmsims** [comment]
I rebooted and it all started working!

Thank you for the help - I just sent you a couple of coffees

```
+ /data/etc/raspberry-pi-backup/ext/dd if=/dev/mmcblk0 of=/mnt/backup/Backups/raspberrypi2/Backup_raspberrypi2_20230607_140435.img bs=1MB status=progress
405000000 bytes (405 MB, 386 MiB) copied, 74 s, 5.5 MB/s
```

**Comment by mr-manuel** [comment]
Good to hear, that now it's working!

Thanks
