### ISSUE TITLE
Value too large for defined data type Error when creating of the backup folder on the remote path.

### ISSUE THREAD

**Issue by scank123** [mr-manuel/raspberry-pi-backup#3]
Hello,

i have running VenusOS Large on my RPI2.
if i start the ./backup i become this error message.

```bash
mkdir: can't create directory '/mnt2/imagebackupnlw/': Value too large for defined data type
Error when creating of the backup folder on the remote path.
```

on my other rasperrys with running raspian i can mout the same serverpath successful.

**Comment by mr-manuel** [comment]
Seems to be an issue of `busybox`. But already the `2` in `/mnt2/` is very strange. Did you modify the script? If not delete it and download it again. 

I found no fix for this other than you create the backup folder on your own. Then it works.

**Comment by scank123** [comment]
hello,

i have added parameters  ,nounix,noserverino in the mount line. now it works on my System.

**Comment by mr-manuel** [comment]
Thanks for the feedback! I will add this.

**Comment by ruildias** [comment]
I just remember that, due to a an issue with SMB, config in my NAS I did the mount manually without additional/optional parameters.
I did the unmount manually an I am doing a backup again ... sorry, I might mislead you ...
In ~1h I will let you know ().

**Comment by ruildias** [comment]
No, the mount was not the issue ...

**Comment by cmock** [comment]
probably comes in 3.60 when it's released, see this commit: https://github.com/victronenergy/meta-victronenergy/commit/a3bb37179ffb1c4963ba63ca442ebdf412a1e4df
