### ISSUE TITLE
deletes backups right after creation

### ISSUE THREAD

**Issue by brandac** [mr-manuel/raspberry-pi-backup#5]
Hi, 

thanks for developing this script, it's great.

I use it on two raspberry's. One with Venus OS and one with raspbian. On Venus OS it works great but on raspbian it deletes the backups it creates immediately after it finishes the creation a new backup. I have to set the backup_count to 0 to not delete all backups again.

Could you please have a look at this?

**Comment by mr-manuel** [comment]
Hi, it will take some time, but I will fix that.
