### ISSUE TITLE
CIFS mount not possible on Venus OS v3.12?

### ISSUE THREAD

**Issue by philippsurf** [mr-manuel/raspberry-pi-backup#6]
When I try to mount my CIFS-share I get the following error:

mount: /mnt: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program._

It looks like that the CIFS utils are not installed in VenusOS v3.12 large?

**Comment by mdkeil** [comment]
I have the same problem with venusOS 3.30, because of the missing mount.cifs command.

Edit: reinstalling raspberry-pi-backup after venusOS-Update does the trick
