### ISSUE TITLE
Backup to USB?

### ISSUE THREAD

**Issue by lfhoward** [mr-manuel/raspberry-pi-backup#7]
Dear Mr-Manuel, 

I have used rpi-clone to clone my raspberry pi SD cards in the past, so that I can just pop in the cloned SD card if the original got corrupted. There is no need for an external computer in this scenario.

Rpi-clone will not work with Venus OS however, so I am very interested in your backup script. I see that your script is designed to create a backup on a remote computer. Can it be used instead to clone the SD card to another SD card located locally on USB? I think the path to the USB drive on Venus would be /run/media/sda1, but I am not sure this would work if your script is expecting a remote connection. Please advise.

Thank you in advance for the clarification. 

P.S. I also use your dbus_serialbattery script on my system and it is awesome.

**Comment by mr-manuel** [comment]
Just change the mount path to your USB mount.

**Comment by lfhoward** [comment]
> Just change the mount path to your USB mount.

Like this? 
![Screenshot from 2024-03-11 20-07-10](https://github.com/mr-manuel/raspberry-pi-backup/assets/99151873/394980f1-ed5e-41a4-910a-9036d122648a)

**Comment by mr-manuel** [comment]
Yes. You also have to disable the mounting process else the script tries to mount that path.

https://github.com/mr-manuel/raspberry-pi-backup/blob/3b3089299e3319f55cc16b6d9b900c5c219185ca/raspberry-pi-backup/backup.sh#L57-L59
