### ISSUE TITLE
Network Error: Software caused connection abort

### ISSUE THREAD

**Issue by roblatour** [mr-manuel/raspberry-pi-backup#8]
First of all, thank you very much for making this backup script available.

I am trying to back up active version of the Victron software running on Venus on a Raspberry Pi Zero 2 W.

For this I am connecting to the Pi using Putty.

However, when I run the ./backup.sh command I a problem occurs.

At first a file seems to be written to my NAS drive (on a QNAP server) but after a period of time usually > 30 seconds, I get a pop-up message that says "Network Error: Software caused connection abort".

On my file server a file is written, it can be of varying size - the last attempt it was 157,435 KB (but I've seen it up to about twice that size) .

I've checked the mount.nfs and mount.cifs files are in the sbin folder.
I've tried enabling SMB 1 when SMB 2 and 3 didn't work on the server.
However, same error each time.

Any help would be appreciated.

Thanks

**Comment by roblatour** [comment]
I also tried the suggestions here: https://windowsreport.com/putty-software-caused-connection-abort/

but they did not resolve the issue - however more data ( 1,085,856 KB ) was transferred before the error message appeared.

**Comment by mr-manuel** [comment]
Unfortunately I never had this error and do not know how to solve it. Maybe someone other can help.

Do you have a stable WiFi connection? What does the ping say, if you ping the Raspberry Pi from another device when you start the backup?

**Comment by roblatour** [comment]
Thank you,

The connection seems stable, its all in my own home network.

The ping shows minimum 17ms, maximum 33m, and average 23 ms and no packet loss when backup is underway.
For reference the ping shows minimum 1ms, maximum 7m, and average 3 ms and no packet loss when backup is not underway.

When the backup is running it is reporting transfer speeds are about 4.4 MB/s.

Do you know if there is a way to stop the Victron app/service from running on Venus while the backup is underway?

I'm thinking if I could stop the Victron app/service, run the backup, and then restart the Victron app/service I might have more success with the backup.


________________________________

**Comment by roblatour** [comment]
I've read that this might be a firewall issue, so I'm currently giving it another run - this time I've opened up the W11 Sandbox so that I can run PuTTY without my third party firewall software on + plus also made the changes noted in the link in my earlier post.   For now this seems to be working, I'm at over 4.3 GB transferred with no issue other than its transferring really slow (4.2 MB/s). 

Out of curiosity, the SD card I am using is a 64GB card.  Is this going to need to transfer 64GB?  If so this may take hours to complete.

Hope the wife doesn't turn on the Microwave.

Will post back here later with results.

**Comment by roblatour** [comment]
Well that worked, but the transfer took a very long time (more than 4 hrs) - as mentioned earlier the micro SD card is 64 GB which  approx. matches the size of the backup file (62,586,880 KB).

In any case, here is what got it to work ...

1.  ran PuTTY in a Windows 11 Sandbox

2.  in PuTTY, prior to connecting, set the following options:
    Connection
	    Seconds between keepalives (0 to turn off) 15
		(checked) Disable Nagle's algortim (TCP_NODELAY option)
	    (checked) Enable TCP Keepalives (SO_KEEPALIVE option)
		Interent protocol version
	  	   (selected) Auto
		
3.  Session
        Entered ip address of raspberry pi zero 2 w
		clicked OK
    
So thanks for your help, and the backup routine!

If you want to leave this issue open for a bit that would be good as I've ordered a OTG Ethernet Hub Adapter for the Pi Zero and can report back hear the transfer time difference after I get it setup.

**Comment by mr-manuel** [comment]
Yes it's copying the whole size of the SD card in this case, even if there is only a few hundreds MB of data. You can compress the backup, then the whitespace is deduplicated.

**Comment by roblatour** [comment]
Yes, compressing the file with 7zip reduced it by an incredible 99.7%; down to only 200,700KB

**Comment by roblatour** [comment]
Just as a final update...

I got my OTG Ethernet adapter today and am running a test with it (it is still running, and has been for some time).  

Here are the perinate points associated with its use:

1. The file is transferring a little less than 3x faster via Ethernet than Wi-Fi (transmission rate is 11.9 MB/s as opposed to 4.2 MB/s)

2. I did not have to run PuTTY in the Windows Sandbox, nor did I need to make any setting changes within PuTTY to get it to work.

I fully expect the transfer to complete - it will just take some more time.

Thanks again for making this script available, if someone else runs it to this same issue in the future I hope these posts will help!

Cheers!

**Comment by roblatour** [comment]
Hi George,

 

Glad its all up and running!

 

Regarding the suspected spam caller, adding to what Eric has written below, with CallClerk if you want you can set up a blacklist entry to block calls based on the caller id name – in your case “Suspected Spam”.

 

However, before CallClerk will block a call based on a blacklisted name it will first check to see if there is an existing CallClerk directory entry for the caller id number.  So in this way even if you phone shows up as Suspected Spam, if you have a CallClerk directory entry for your number and have set it to be a familiar caller, then then call will not be blocked.

 

For more information on how CallClerk determines if a call should be blocked as well as more information on black and white lists please see: https://www.callclerk.com/phone/hlpCallClerkCallBlocking.html

 

Best Regards,


Rob

 

From: GetFaxing ***@***.***> 
Sent: Tuesday, April 2, 2024 12:00 PM
To: George S. Augustas ***@***.***>
Cc: ***@***.***
Subject: Re: Problem with Call Clerk

 

Hello George,

 

Glad to hear you received the modem.

 

From what you describe it appears you have Digital Phone Call Protect enabled on your AT&T phone line?  I am not too familiar with this service but within your MyAT&T online account settings you may be able to adjust the level of protection or disable this option on your phone line to allow CallClerk to handle all the spam caller ID protection. 

 

Rob @ CallClerk may have some additional suggestions on the CallClerk software side. 

 

Regards,

Eric

GetFaxing.com

 <https://www.getfaxing.com/> https://www.getfaxing.com

 <https://www.getfaxing.com/shop> https://www.getfaxing.com/shop

We would love your feedback. Post a review to our profile. 

 <https://g.page/r/Cd2pFD6GiJZ0EAI/review> https://g.page/r/Cd2pFD6GiJZ0EAI/review





On Apr 2, 2024, at 11:28 AM, George S. Augustas ***@***.*** ***@***.***> > wrote:

﻿

Well, I have good news and good news.

The FAX modem arrived today. I plugged it into a USB port. The computer recognised it as
            “Conexant USB CX93010 ACF Fax Voice Modem.”

However, Call Clerk did not see it until I had removed the old modem from the PCI slot. I had to disconnect the USB modem and connect it again and restart Call Clerk. Then it was recognised. I used the TAPI setting.

I called the house phone from my Magic Jack, which is on the Allowed list. The number was recognised, and Call Clerk announced the call. So it is working again.

Now this is where things get interesting: The caller ID from the phone company (AT&T) showed the Caller ID as “Suspected Spam.” Almost immediately after that call, a call from an unknown caller came through, and that caller also showed “Suspected Spam.” So apparently, AT&T is flagging calls as “Suspected Spam” when it cannot identify the caller. If I allow “Suspected Spam” calls to ring in, I get deluged with them. So I am not certain of the best way to set up these kinds of calls. I currently have them set to Blocked unless they are on the Allowed List, but I worry that I might block a call that I might have wanted.

George S. Augustas

“It takes no more time to see the good side of life than the bad.” —Jimmy Buffet

 

From: ***@***.*** ***@***.***>  ***@***.*** ***@***.***> > 
Sent: 27 Mar 2024 15:27
To: 'George S. Augustas' ***@***.*** ***@***.***> >
Subject: RE: Problem with Call Clerk

 

Thanks for the update, when you get the modem if you have any troubles getting it to work with CallClerk just let me know.

 

However, a couple points:

1.       it would likely be best to disable the old modem in Device Manager before plugging in the new one; to do this just go into Windows Device Manager, click on modems, and then right click on your modem, and then select ‘Disable device’.  Another option would be of course to physically remove it.

2.       once the new modem is installed, please go into the CallClerk – Settings – Modem window and click on the ‘Auto Set’ button; this will cause CallClerk to re-inventory your modems (of which there should only be one appearing in the dropdown box - assuming you completed step 1 above).

 

Best Regards, (and please call me):

 

Rob
